apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-handler-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-handler-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-handler-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: db-handler-sa
  namespace: default
roleRef:
  kind: Role
  name: db-handler-role
  apiGroup: rbac.authorization.k8s.io

