apiVersion: v1
kind: Service
metadata:
  name: beverage-service
  labels:
    app: beverage-service
spec:
  selector:
    app: beverage-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
  labels:
    app: management-service
spec:
  selector:
    app: management-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ui-module
  labels:
    app: ui-module
spec:
  selector:
    app: ui-module
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db-handler
  labels:
    app: db-handler
spec:
  selector:
    app: db-handler
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP
